export type BadgeStatus = "unlocked" | "locked" | "in-progress";
export type BadgeTier = "common" | "rare" | "epic" | "legendary";
export type BadgeCategory =
  | "progression"
  | "performance"
  | "engagement"
  | "accomplissement"
  | "contenus"
  | "formateurs"
  | "speciaux"
  | "niveaux";

export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: BadgeCategory;
  status: BadgeStatus;
  tier: BadgeTier;
  progress?: number;
  unlockedAt?: string;
  xpReward: number;
  condition: string;
  gradient: string;
  glowColor: string;
}

export const categoryMeta: Record<
  BadgeCategory,
  { label: string; icon: string; color: string; gradient: string }
> = {
  progression: {
    label: "Progression",
    icon: "🎓",
    color: "#10b981",
    gradient: "from-emerald-500 to-teal-600",
  },
  performance: {
    label: "Performance",
    icon: "🧠",
    color: "#f59e0b",
    gradient: "from-amber-500 to-orange-600",
  },
  engagement: {
    label: "Engagement",
    icon: "⏱️",
    color: "#3b82f6",
    gradient: "from-blue-500 to-cyan-600",
  },
  accomplissement: {
    label: "Accomplissement",
    icon: "🏅",
    color: "#8b5cf6",
    gradient: "from-violet-500 to-purple-600",
  },
  contenus: {
    label: "Contenus",
    icon: "🧩",
    color: "#ec4899",
    gradient: "from-pink-500 to-rose-600",
  },
  formateurs: {
    label: "Formateurs",
    icon: "👨‍🏫",
    color: "#f97316",
    gradient: "from-orange-500 to-red-500",
  },
  speciaux: {
    label: "Spéciaux",
    icon: "🌟",
    color: "#6366f1",
    gradient: "from-indigo-500 to-violet-600",
  },
  niveaux: {
    label: "Niveaux",
    icon: "📊",
    color: "#14b8a6",
    gradient: "from-teal-500 to-cyan-500",
  },
};

// Catalogue complet — 33 badges (status mis à jour dynamiquement depuis backend)
export const badgesCatalogue: Omit<
  Badge,
  "status" | "unlockedAt" | "progress"
>[] = [
  // ─── PROGRESSION ───────────────────────────────────────────
  {
    id: "premier_contenu",
    name: "Premier Pas",
    description: "Premier contenu consulté",
    icon: "🟢",
    category: "progression",
    tier: "common",
    xpReward: 50,
    condition: "Consulter votre premier contenu",
    gradient: "from-emerald-400 to-teal-500",
    glowColor: "rgba(16,185,129,0.5)",
  },
  {
    id: "module_complete",
    name: "Module Complété",
    description: "100% d'un module terminé avec succès",
    icon: "📘",
    category: "progression",
    tier: "common",
    xpReward: 100,
    condition: "Terminer un module à 100%",
    gradient: "from-blue-400 to-emerald-500",
    glowColor: "rgba(59,130,246,0.5)",
  },
  {
    id: "formation_complete",
    name: "Formation Terminée",
    description: "Une formation complète terminée",
    icon: "📚",
    category: "progression",
    tier: "rare",
    xpReward: 250,
    condition: "Compléter entièrement une formation",
    gradient: "from-emerald-500 to-cyan-500",
    glowColor: "rgba(16,185,129,0.6)",
  },
  {
    id: "apprenant_actif",
    name: "Apprenant Actif",
    description: "5 modules enchaînés en progression",
    icon: "🔥",
    category: "progression",
    tier: "rare",
    xpReward: 200,
    condition: "Compléter 5 modules consécutifs",
    gradient: "from-orange-400 to-red-500",
    glowColor: "rgba(249,115,22,0.5)",
  },
  {
    id: "progression_rapide",
    name: "Progression Rapide",
    description: "Formation terminée en un temps record",
    icon: "🚀",
    category: "progression",
    tier: "epic",
    xpReward: 400,
    condition: "Terminer une formation dans le délai minimum",
    gradient: "from-violet-400 to-indigo-500",
    glowColor: "rgba(139,92,246,0.5)",
  },
  // ─── PERFORMANCE ───────────────────────────────────────────
  {
    id: "quiz_reussi",
    name: "Quiz Réussi",
    description: "Seuil de réussite atteint au quiz",
    icon: "🎯",
    category: "performance",
    tier: "common",
    xpReward: 75,
    condition: "Dépasser le seuil de réussite d'un quiz",
    gradient: "from-amber-400 to-yellow-500",
    glowColor: "rgba(245,158,11,0.5)",
  },
  {
    id: "quiz_parfait",
    name: "Score Parfait",
    description: "100% au quiz — perfection absolue",
    icon: "💯",
    category: "performance",
    tier: "epic",
    xpReward: 500,
    condition: "Obtenir un score de 100% à un quiz",
    gradient: "from-amber-500 to-orange-600",
    glowColor: "rgba(245,158,11,0.7)",
  },
  {
    id: "premier_coup",
    name: "Réussite du Premier Coup",
    description: "Quiz validé sans tentative multiple",
    icon: "⚡",
    category: "performance",
    tier: "rare",
    xpReward: 150,
    condition: "Réussir un quiz à la première tentative",
    gradient: "from-yellow-400 to-amber-500",
    glowColor: "rgba(234,179,8,0.6)",
  },
  {
    id: "en_amelioration",
    name: "En Amélioration",
    description: "Score amélioré entre deux tentatives",
    icon: "📈",
    category: "performance",
    tier: "common",
    xpReward: 100,
    condition: "Améliorer son score entre deux tentatives",
    gradient: "from-green-400 to-emerald-500",
    glowColor: "rgba(34,197,94,0.5)",
  },
  {
    id: "top_score",
    name: "Top Score",
    description: "Meilleur score de la promotion",
    icon: "🏆",
    category: "performance",
    tier: "legendary",
    xpReward: 1000,
    condition: "Avoir le meilleur score dans une formation",
    gradient: "from-yellow-300 to-amber-500",
    glowColor: "rgba(252,211,77,0.8)",
  },
  // ─── ENGAGEMENT ────────────────────────────────────────────
  {
    id: "assidu",
    name: "Assidu",
    description: "5 contenus consultés en 1 journée",
    icon: "📅",
    category: "engagement",
    tier: "common",
    xpReward: 80,
    condition: "Se connecter et consulter 5 contenus par jour",
    gradient: "from-blue-400 to-cyan-500",
    glowColor: "rgba(59,130,246,0.5)",
  },
  {
    id: "temps_investi",
    name: "Temps Investi",
    description: "X heures passées sur la plateforme",
    icon: "⏳",
    category: "engagement",
    tier: "rare",
    xpReward: 200,
    condition: "Passer 20 heures sur la plateforme",
    gradient: "from-cyan-400 to-blue-500",
    glowColor: "rgba(6,182,212,0.5)",
  },
  {
    id: "perseverant",
    name: "Persévérant",
    description: "Plusieurs tentatives sur un même quiz",
    icon: "🔁",
    category: "engagement",
    tier: "common",
    xpReward: 60,
    condition: "Tenter un quiz plus de 3 fois",
    gradient: "from-indigo-400 to-blue-500",
    glowColor: "rgba(99,102,241,0.5)",
  },
  {
    id: "objectif_atteint",
    name: "Objectif Atteint",
    description: "Formation commencée et terminée",
    icon: "🎯",
    category: "engagement",
    tier: "rare",
    xpReward: 300,
    condition: "Terminer une formation commencée",
    gradient: "from-sky-400 to-indigo-500",
    glowColor: "rgba(14,165,233,0.5)",
  },
  // ─── ACCOMPLISSEMENT ───────────────────────────────────────
  {
    id: "certifie",
    name: "Certifié",
    description: "Certificat officiel obtenu",
    icon: "🎓",
    category: "accomplissement",
    tier: "epic",
    xpReward: 750,
    condition: "Obtenir un certificat de formation",
    gradient: "from-violet-500 to-purple-600",
    glowColor: "rgba(139,92,246,0.7)",
  },
  {
    id: "mention_excellent",
    name: "Excellence",
    description: "Mention Excellent — moyenne ≥ 95%",
    icon: "🥇",
    category: "accomplissement",
    tier: "legendary",
    xpReward: 1500,
    condition: "Obtenir la mention Excellent",
    gradient: "from-yellow-300 to-amber-400",
    glowColor: "rgba(252,211,77,0.8)",
  },
  {
    id: "mention_tres_bien",
    name: "Très Bien",
    description: "Mention Très Bien — moyenne ≥ 85%",
    icon: "🥈",
    category: "accomplissement",
    tier: "epic",
    xpReward: 800,
    condition: "Obtenir la mention Très Bien",
    gradient: "from-slate-300 to-gray-400",
    glowColor: "rgba(148,163,184,0.6)",
  },
  {
    id: "mention_bien",
    name: "Bien",
    description: "Mention Bien — moyenne ≥ 70%",
    icon: "🥉",
    category: "accomplissement",
    tier: "rare",
    xpReward: 400,
    condition: "Obtenir la mention Bien",
    gradient: "from-orange-300 to-amber-500",
    glowColor: "rgba(251,146,60,0.5)",
  },
  // ─── CONTENUS ──────────────────────────────────────────────
  {
    id: "amateur_videos",
    name: "Amateur de Vidéos",
    description: "Plusieurs vidéos de formation complétées",
    icon: "🎥",
    category: "contenus",
    tier: "common",
    xpReward: 80,
    condition: "Regarder 10 vidéos de formation",
    gradient: "from-pink-400 to-rose-500",
    glowColor: "rgba(236,72,153,0.5)",
  },
  {
    id: "lecteur_assidu",
    name: "Lecteur Assidu",
    description: "Plusieurs PDF lus et complétés",
    icon: "📄",
    category: "contenus",
    tier: "common",
    xpReward: 80,
    condition: "Lire 5 documents PDF",
    gradient: "from-rose-400 to-pink-500",
    glowColor: "rgba(244,63,94,0.5)",
  },
  {
    id: "explorateur_media",
    name: "Explorateur Multimédia",
    description: "Tous types de contenus consultés",
    icon: "🎧",
    category: "contenus",
    tier: "rare",
    xpReward: 200,
    condition: "Consulter vidéo, PDF, audio et SCORM",
    gradient: "from-fuchsia-400 to-pink-600",
    glowColor: "rgba(192,38,211,0.5)",
  },
  // ─── FORMATEURS ────────────────────────────────────────────
  {
    id: "premier_cours",
    name: "Premier Cours Publié",
    description: "Votre première formation publiée",
    icon: "🧑‍🏫",
    category: "formateurs",
    tier: "rare",
    xpReward: 300,
    condition: "Publier une première formation",
    gradient: "from-orange-400 to-red-500",
    glowColor: "rgba(249,115,22,0.5)",
  },
  {
    id: "formateur_apprecie",
    name: "Formateur Apprécié",
    description: "Évaluations excellentes de vos apprenants",
    icon: "⭐",
    category: "formateurs",
    tier: "epic",
    xpReward: 600,
    condition: "Obtenir une note moyenne ≥ 4.5/5",
    gradient: "from-yellow-400 to-orange-500",
    glowColor: "rgba(245,158,11,0.6)",
  },
  {
    id: "formateur_perf",
    name: "Formateur Performant",
    description: "Taux de réussite élevé dans vos formations",
    icon: "📊",
    category: "formateurs",
    tier: "epic",
    xpReward: 700,
    condition: "Avoir un taux de réussite ≥ 80%",
    gradient: "from-red-400 to-orange-600",
    glowColor: "rgba(239,68,68,0.5)",
  },
  {
    id: "formateur_actif",
    name: "Formateur Actif",
    description: "Plusieurs formations créées et actives",
    icon: "🔥",
    category: "formateurs",
    tier: "rare",
    xpReward: 400,
    condition: "Créer et publier 5 formations",
    gradient: "from-orange-500 to-red-600",
    glowColor: "rgba(249,115,22,0.6)",
  },
  // ─── SPÉCIAUX ──────────────────────────────────────────────
  {
    id: "explorateur",
    name: "Explorateur",
    description: "Découvrez de nouvelles formations",
    icon: "🕵️",
    category: "speciaux",
    tier: "rare",
    xpReward: 150,
    condition: "Consulter 5 formations différentes",
    gradient: "from-indigo-400 to-violet-500",
    glowColor: "rgba(99,102,241,0.5)",
  },
  {
    id: "curieux",
    name: "Curieux",
    description: "Tester différents domaines de formation",
    icon: "🧪",
    category: "speciaux",
    tier: "rare",
    xpReward: 200,
    condition: "S'inscrire dans 3 domaines distincts",
    gradient: "from-violet-400 to-indigo-600",
    glowColor: "rgba(139,92,246,0.5)",
  },
  {
    id: "early_adopter",
    name: "Early Adopter",
    description: "Parmi les premiers utilisateurs",
    icon: "💡",
    category: "speciaux",
    tier: "legendary",
    xpReward: 1000,
    condition: "Être parmi les 100 premiers inscrits",
    gradient: "from-yellow-400 to-indigo-500",
    glowColor: "rgba(99,102,241,0.8)",
  },
  {
    id: "objectif_perso",
    name: "Objectif Personnel",
    description: "Objectif personnel atteint",
    icon: "🎯",
    category: "speciaux",
    tier: "epic",
    xpReward: 500,
    condition: "Atteindre un objectif personnel défini",
    gradient: "from-purple-400 to-pink-500",
    glowColor: "rgba(168,85,247,0.5)",
  },
  // ─── NIVEAUX ───────────────────────────────────────────────
  {
    id: "niveau_bronze",
    name: "Niveau Bronze",
    description: "Premiers modules complétés",
    icon: "🥉",
    category: "niveaux",
    tier: "common",
    xpReward: 100,
    condition: "Compléter 5 modules",
    gradient: "from-orange-300 to-amber-600",
    glowColor: "rgba(217,119,6,0.5)",
  },
  {
    id: "niveau_argent",
    name: "Niveau Argent",
    description: "Vous progressez régulièrement",
    icon: "🥈",
    category: "niveaux",
    tier: "rare",
    xpReward: 300,
    condition: "Compléter 15 modules",
    gradient: "from-slate-300 to-zinc-500",
    glowColor: "rgba(148,163,184,0.5)",
  },
  {
    id: "niveau_or",
    name: "Niveau Or",
    description: "Excellent parcours",
    icon: "🥇",
    category: "niveaux",
    tier: "epic",
    xpReward: 600,
    condition: "Compléter 30 modules",
    gradient: "from-yellow-300 to-amber-500",
    glowColor: "rgba(234,179,8,0.7)",
  },
  {
    id: "niveau_expert",
    name: "Niveau Expert",
    description: "Le summum de la maîtrise",
    icon: "💎",
    category: "niveaux",
    tier: "legendary",
    xpReward: 2000,
    condition: "Compléter 50 modules",
    gradient: "from-cyan-300 via-blue-400 to-violet-500",
    glowColor: "rgba(99,102,241,0.9)",
  },
];

// Mapper badge backend → Badge frontend
export function mapBackendBadge(
  b: {
    id: string;
    code: string;
    nom: string;
    description: string;
    icone: string;
    obtenu_le?: string;
  },
  status: BadgeStatus = "unlocked",
): Badge {
  const cat = badgesCatalogue.find((c) => c.id === b.code);
  return {
    id: b.code,
    name: b.nom,
    description: b.description,
    icon: b.icone,
    category: cat?.category ?? "speciaux",
    status,
    tier: cat?.tier ?? "common",
    xpReward: cat?.xpReward ?? 50,
    condition: cat?.condition ?? b.description,
    gradient: cat?.gradient ?? "from-blue-500 to-purple-600",
    glowColor: cat?.glowColor ?? "rgba(99,102,241,0.5)",
    unlockedAt: b.obtenu_le,
  };
}
